# Generated by Django 5.1.4 on 2024-12-07 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название уровня')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('description', models.TextField(verbose_name='Краткое содержание')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios/', verbose_name='Аудио')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('test_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на тест')),
                ('additional_links', models.TextField(blank=True, null=True, verbose_name='Дополнительные материалы (ссылки)')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.level', verbose_name='Уровень')),
            ],
        ),
    ]
