# Generated by Django 5.1.4 on 2024-12-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_level_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=2)),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=255)),
            ],
        ),
    ]
