# Generated by Django 5.1.4 on 2024-12-07 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avtor', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
